version: "3"
services:

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  recipe-crud:
      image: "recipe-filter"
      environment:
        -SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
        -SPRING_DATASOURE_USERNAME: "postgres"
        -SPRING_DATASOURCE_PASSWORD: "postgres"
      ports:
        - "8080:8080"
      depends_on:
        - db